create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  name text not null unique,
  gender text not null,
  affiliation text not null,
  nen_type text not null,
  origin text not null,
  first_arc text not null,
  status text not null,
  role text not null,
  age_group text not null,
  quote text not null,
  nen_hint text not null,
  silhouette text not null,
  anime_only boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.leaderboard (
  player_name text primary key,
  score integer not null default 0,
  streak integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.characters enable row level security;
alter table public.leaderboard enable row level security;

create policy "characters are readable" on public.characters
for select using (true);

create policy "leaderboard is readable" on public.leaderboard
for select using (true);

create policy "leaderboard can be upserted by anyone" on public.leaderboard
for insert with check (true);

create policy "leaderboard can be updated by anyone" on public.leaderboard
for update using (true) with check (true);

insert into public.characters
(name, gender, affiliation, nen_type, origin, first_arc, status, role, age_group, quote, nen_hint, silhouette)
values
('Gon Freecss','Masculino','Caçador','Reforço','Ilha da Baleia','Exame Hunter','Vivo','Protagonista','Criança','Eu quero descobrir por que meu pai quis tanto ser Hunter.','A energia é concentrada em golpes diretos e explosivos.','Cabelo espetado, baixa estatura e roupa verde.'),
('Killua Zoldyck','Masculino','Família Zoldyck','Transmutação','Montanha Kukuroo','Exame Hunter','Vivo','Protagonista','Criança','Eu sou amigo dele. Isso basta.','Seu Nen imita eletricidade e aumenta reflexos em combate.','Cabelo branco bagunçado, expressão calma e postura ágil.'),
('Kurapika','Masculino','Clã Kurta','Materialização','Vila Kurta','Exame Hunter','Vivo','Aliado principal','Jovem','Eu não temo a morte. Temo que minha raiva desapareça.','Correntes materializadas são usadas com regras e restrições severas.','Cabelo loiro, roupa tradicional e olhar determinado.'),
('Leorio Paradinight','Masculino','Caçador','Emissão','Desconhecida','Exame Hunter','Vivo','Aliado principal','Jovem adulto','Eu vou ser médico. E vou salvar quem não pode pagar.','Seu golpe atravessa distância usando emissão de aura.','Terno, óculos escuros e aparência de adulto comum.'),
('Hisoka Morow','Masculino','Independente','Transmutação','Desconhecida','Exame Hunter','Vivo','Antagonista','Adulto','O verdadeiro prazer está em enfrentar alguém promissor.','Sua aura tem propriedades de borracha e goma.','Visual de mágico, cartas e maquiagem marcante.'),
('Chrollo Lucilfer','Masculino','Trupe Fantasma','Especialização','Cidade Meteoro','Yorknew City','Vivo','Antagonista','Adulto','Não há motivo. Nós apenas fazemos.','Rouba habilidades de Nen e as registra em um livro.','Cruz na testa, casaco escuro e livro nas mãos.'),
('Meruem','Masculino','Formigas Quimera','Especialização','NGL','Formigas Quimera','Morto','Antagonista','Desconhecida','O que significa ser rei?','Sua aura cresce ao consumir outros seres com Nen.','Cauda, armadura natural e postura de rei.'),
('Neferpitou','Indefinido','Formigas Quimera','Especialização','NGL','Formigas Quimera','Morto','Antagonista','Desconhecida','Preciso proteger o Rei.','Usa marionetes e técnicas médicas ligadas a aura.','Traços felinos, orelhas de gato e cauda.'),
('Biscuit Krueger','Feminino','Caçador','Transmutação','Desconhecida','Greed Island','Vivo','Mentora','Adulto','Vocês dois ainda são diamantes brutos.','Aura voltada a transformação, cura e condicionamento.','Aparência pequena e fofa que esconde força monstruosa.'),
('Isaac Netero','Masculino','Associação Hunter','Reforço','Desconhecida','Exame Hunter','Morto','Mentor','Idoso','A evolução humana é infinita.','Ataques velozes associados a uma estátua gigantesca.','Idoso de bigode, roupa de artes marciais e aura serena.')
on conflict (name) do nothing;

insert into public.leaderboard (player_name, score, streak) values
('GingFreecss_404', 1260, 14),
('BungeeGum', 1120, 11),
('ChainUser', 980, 8)
on conflict (player_name) do nothing;
