export type Character = {
  id?: number;
  name: string;
  gender: string;
  affiliation: string;
  nen_type: string;
  origin: string;
  first_arc: string;
  status: string;
  role: string;
  age_group: string;
  quote: string;
  nen_hint: string;
  silhouetteImage: string;
};

export const fallbackCharacters: Character[] = [
{
  name: 'Gon Freecss',
  gender: 'Masculino',
  affiliation: 'Caçador',
  nen_type: 'Reforço',
  origin: 'Ilha da Baleia',
  first_arc: 'Exame Hunter',
  status: 'Vivo',
  role: 'Protagonista',
  age_group: 'Adolescente',
  quote: 'Não importa...',
  nen_hint: 'Jajanken',
  silhouetteImage: '/silhouettes/gon.png'
},
  { name: 'Killua Zoldyck', gender: 'Masculino', affiliation: 'Família Zoldyck', nen_type: 'Transmutação', origin: 'Montanha Kukuroo', first_arc: 'Exame Hunter', status: 'Vivo', role: 'Protagonista', age_group: 'Criança', quote: 'Eu sou amigo dele. Isso basta.', nen_hint: 'Seu Nen imita eletricidade e aumenta reflexos em combate.', silhouetteImage: "/silhouettes/killua.svg", },
  { name: 'Kurapika', gender: 'Masculino', affiliation: 'Clã Kurta', nen_type: 'Materialização', origin: 'Vila Kurta', first_arc: 'Exame Hunter', status: 'Vivo', role: 'Aliado principal', age_group: 'Jovem', quote: 'Eu não temo a morte. Temo que minha raiva desapareça.', nen_hint: 'Correntes materializadas são usadas com regras e restrições severas.', silhouetteImage: "/silhouettes/kurapika.svg", },
  { name: 'Leorio Paradinight', gender: 'Masculino', affiliation: 'Caçador', nen_type: 'Emissão', origin: 'Desconhecida', first_arc: 'Exame Hunter', status: 'Vivo', role: 'Aliado principal', age_group: 'Jovem adulto', quote: 'Eu vou ser médico. E vou salvar quem não pode pagar.', nen_hint: 'Seu golpe atravessa distância usando emissão de aura.', silhouetteImage: "/silhouettes/leorio.svg", },
  { name: 'Hisoka Morow', gender: 'Masculino', affiliation: 'Independente', nen_type: 'Transmutação', origin: 'Desconhecida', first_arc: 'Exame Hunter', status: 'Vivo', role: 'Antagonista', age_group: 'Adulto', quote: 'O verdadeiro prazer está em enfrentar alguém promissor.', nen_hint: 'Sua aura tem propriedades de borracha e goma.', silhouetteImage: "/silhouettes/hisoka.svg", },
{ 
  name: 'Chrollo Lucilfer',
  gender: 'Masculino',
  affiliation: 'Trupe Fantasma',
  nen_type: 'Especialização',
  origin: 'Cidade Meteoro',
  first_arc: 'Yorknew City',
  status: 'Vivo',
  role: 'Antagonista',
  age_group: 'Adulto',
  quote: 'Não há motivo. Nós apenas fazemos.',
  nen_hint: 'Rouba habilidades de Nen e as registra em um livro.',
  silhouetteImage: "/silhouettes/chrollo.png",},
  { name: 'Meruem', gender: 'Masculino', affiliation: 'Formigas Quimera', nen_type: 'Especialização', origin: 'NGL', first_arc: 'Formigas Quimera', status: 'Morto', role: 'Antagonista', age_group: 'Desconhecida', quote: 'O que significa ser rei?', nen_hint: 'Sua aura cresce ao consumir outros seres com Nen.', silhouetteImage: "/silhouettes/meruem.svg", },
  { name: 'Neferpitou', gender: 'Indefinido', affiliation: 'Formigas Quimera', nen_type: 'Especialização', origin: 'NGL', first_arc: 'Formigas Quimera', status: 'Morto', role: 'Antagonista', age_group: 'Desconhecida', quote: 'Preciso proteger o Rei.', nen_hint: 'Usa marionetes e técnicas médicas ligadas a aura.', silhouetteImage: "/silhouettes/pitou.svg", },
  { name: 'Biscuit Krueger', gender: 'Feminino', affiliation: 'Caçador', nen_type: 'Transmutação', origin: 'Desconhecida', first_arc: 'Greed Island', status: 'Vivo', role: 'Mentora', age_group: 'Adulto', quote: 'Vocês dois ainda são diamantes brutos.', nen_hint: 'Aura voltada a transformação, cura e condicionamento.', silhouetteImage: 'Aparência pequena e fofa que esconde força monstruosa.' },
  { name: 'Isaac Netero', gender: 'Masculino', affiliation: 'Associação Hunter', nen_type: 'Reforço', origin: 'Desconhecida', first_arc: 'Exame Hunter', status: 'Morto', role: 'Mentor', age_group: 'Idoso', quote: 'A evolução humana é infinita.', nen_hint: 'Ataques velozes associados a uma estátua gigantesca.', silhouetteImage: "/silhouettes/netero.svg", },
{
  name: "Pariston Hill",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Eleição do Presidente Hunter",
  status: "Vivo",
  role: "Ex-vice-presidente da Associação Hunter",
  age_group: "Adulto",
  quote: "Eu gosto quando as pessoas me odeiam.",
  nen_hint: "Manipulação política e inteligência estratégica.",
  silhouetteImage: "/silhouettes/pariston.svg",
},

{
  name: "Cheadle Yorkshire",
  gender: "Feminino",
  affiliation: "Zodíacos",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Eleição do Presidente Hunter",
  status: "Vivo",
  role: "Médica e presidente da Associação Hunter",
  age_group: "Adulta",
  quote: "Precisamos agir com lógica e responsabilidade.",
  nen_hint: "Habilidades médicas e intelectuais avançadas.",
  silhouetteImage: "/silhouettes/cheadle.svg",
},

{
  name: "Botobai Gigante",
  gender: "Masculino",
  affiliation: "Zodíacos",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Eleição do Presidente Hunter",
  status: "Vivo",
  role: "Terrorist Hunter",
  age_group: "Adulto",
  quote: "A justiça precisa ser mantida.",
  nen_hint: "Presença intimidadora e força de combate.",
  silhouetteImage: "/silhouettes/botobai.svg",
},

{
  name: "Mizaistom Nana",
  gender: "Masculino",
  affiliation: "Zodíacos",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Eleição do Presidente Hunter",
  status: "Vivo",
  role: "Crime Hunter",
  age_group: "Adulto",
  quote: "A lei existe por um motivo.",
  nen_hint: "Investigação, análise e estratégias jurídicas.",
  silhouetteImage: "/silhouettes/mizaistom.svg",
},

{
  name: "Kanzai",
  gender: "Masculino",
  affiliation: "Zodíacos",
  nen_type: "Reforço",
  origin: "Desconhecida",
  first_arc: "Eleição do Presidente Hunter",
  status: "Vivo",
  role: "Hunter de combate",
  age_group: "Adulto",
  quote: "Vamos resolver isso na pancada!",
  nen_hint: "Estilo impulsivo e focado em força física.",
  silhouetteImage: "/silhouettes/kanzai.svg",
},

{
  name: "Ging Freecss",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Especialização",
  origin: "Ilha da Baleia",
  first_arc: "Greed Island",
  status: "Vivo",
  role: "Ruínas Hunter",
  age_group: "Adulto",
  quote: "Você deve aproveitar os pequenos desvios.",
  nen_hint: "Capacidade absurda de adaptação e talento Nen.",
  silhouetteImage: "/silhouettes/ging.svg",
},

{
  name: "Morel Mackernasey",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Sea Hunter",
  age_group: "Adulto",
  quote: "Experiência vence arrogância.",
  nen_hint: "Usa fumaça e estratégia em combate.",
  silhouetteImage: "/silhouettes/morel.svg",
},

{
  name: "Tsezguerra",
  gender: "Masculino",
  affiliation: "Caçadores de Greed Island",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Greed Island",
  status: "Vivo",
  role: "Hunter Jackpot",
  age_group: "Adulto",
  quote: "Nem toda vitória vem da força bruta.",
  nen_hint: "Experiência e liderança em missões perigosas.",
  silhouetteImage: "/silhouettes/tsezguerra.svg",
},

{
  name: "Goreinu",
  gender: "Masculino",
  affiliation: "Jogadores de Greed Island",
  nen_type: "Emissão",
  origin: "Desconhecida",
  first_arc: "Greed Island",
  status: "Vivo",
  role: "Jogador de Greed Island",
  age_group: "Adulto",
  quote: "Meus gorilas lutam melhor do que muita gente.",
  nen_hint: "Invoca gorilas ligados a troca de posição.",
  silhouetteImage: "/silhouettes/goreinu.svg",
},

{
  name: "Hanzo",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Transmutação",
  origin: "Japão",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Ninja e Hunter",
  age_group: "Adulto",
  quote: "Eu treinei mais do que você imagina.",
  nen_hint: "Habilidades furtivas e técnicas ninja.",
  silhouetteImage: "/silhouettes/hanzo.svg",
},

{
  name: "Illumi Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Manipulação",
  origin: "Montanha Kukuroo",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Assassino",
  age_group: "Adulto",
  quote: "Killua pertence à família.",
  nen_hint: "Usa agulhas para controlar pessoas e alterar aparência.",
  silhouetteImage: "/silhouettes/illumi.svg",
},

{
  name: "Kite",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Especialização",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Morto",
  role: "Hunter discípulo de Ging",
  age_group: "Adulto",
  quote: "Nunca subestime a natureza.",
  nen_hint: "Arma aleatória invocada por Crazy Slots.",
  silhouetteImage: "/silhouettes/kite.svg",
},

{
  name: "Knov",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Conjuração",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Hunter estrategista",
  age_group: "Adulto",
  quote: "O medo pode destruir qualquer homem.",
  nen_hint: "Cria dimensões e portais secretos.",
  silhouetteImage: "/silhouettes/knov.svg",
},

{
  name: "Knuckle Bine",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Emissão",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Discípulo de Morel",
  age_group: "Adulto",
  quote: "Você não parece um cara ruim.",
  nen_hint: "Empresta aura ao inimigo usando APR.",
  silhouetteImage: "/silhouettes/knuckle.svg",
},

{
  name: "Palm Siberia",
  gender: "Feminino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Discípula de Knov",
  age_group: "Adulta",
  quote: "Meu amor pode virar obsessão.",
  nen_hint: "Habilidades ligadas a vigilância e cabelo.",
  silhouetteImage: "/silhouettes/palm.svg",
},

{
  name: "Shalnark",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Manipulação",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Morto",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Controle é tudo em batalha.",
  nen_hint: "Controla pessoas usando antenas especiais.",
  silhouetteImage: "/silhouettes/shalnark.svg",
},

{
  name: "Shoot McMahon",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Discípulo de Morel",
  age_group: "Adulto",
  quote: "Eu preciso superar meu medo.",
  nen_hint: "Mãos flutuantes e técnicas de aprisionamento.",
  silhouetteImage: "/silhouettes/shoot.svg",
},

{
  name: "Wing",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Arena Celestial",
  status: "Vivo",
  role: "Mestre Nen",
  age_group: "Adulto",
  quote: "Nen deve ser aprendido com responsabilidade.",
  nen_hint: "Grande domínio teórico e prático de Nen.",
  silhouetteImage: "/silhouettes/wing.svg",
},
{
  name: "Tonpa",
  gender: "Masculino",
  affiliation: "Participantes do Exame Hunter",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Sabotador veterano",
  age_group: "Adulto",
  quote: "Novatos sempre caem nos mesmos truques.",
  nen_hint: "Especialista em manipulação psicológica.",
  silhouetteImage: "/silhouettes/tonpa.svg",
},
{
  name: "Zepile",
  gender: "Masculino",
  affiliation: "Mercado de antiguidades",
  nen_type: "Desconhecido",
  origin: "Yorknew City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Colecionador e falsificador",
  age_group: "Adulto",
  quote: "O valor de um objeto depende da história dele.",
  nen_hint: "Grande conhecimento sobre relíquias e itens raros.",
  silhouetteImage: "/silhouettes/zepile.svg",
},

{
  name: "Mito Freecss",
  gender: "Feminino",
  affiliation: "Família Freecss",
  nen_type: "Desconhecido",
  origin: "Ilha da Baleia",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Tia de Gon",
  age_group: "Adulta",
  quote: "Gon sempre foi impossível de segurar.",
  nen_hint: "Figura materna extremamente protetora.",
  silhouetteImage: "/silhouettes/mito.svg",
},

{
  name: "Zeno Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Transmutação",
  origin: "Montanha Kukuroo",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Assassino veterano",
  age_group: "Idoso",
  quote: "Assassinato é apenas trabalho.",
  nen_hint: "Dragões de aura e enorme experiência em combate.",
  silhouetteImage: "/silhouettes/zeno.svg",
},

{
  name: "Silva Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Transmutação",
  origin: "Montanha Kukuroo",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Líder da família Zoldyck",
  age_group: "Adulto",
  quote: "Killua deve escolher seu próprio caminho.",
  nen_hint: "Aura explosiva e força física monstruosa.",
  silhouetteImage: "/silhouettes/silva.svg",
},

{
  name: "Milluki Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Desconhecido",
  origin: "Montanha Kukuroo",
  first_arc: "Família Zoldyck",
  status: "Vivo",
  role: "Especialista em tecnologia",
  age_group: "Adulto",
  quote: "Meus gadgets resolvem qualquer problema.",
  nen_hint: "Grande inteligência e conhecimento tecnológico.",
  silhouetteImage: "/silhouettes/milluki.svg",
},

{
  name: "Alluka Zoldyck",
  gender: "Feminino",
  affiliation: "Família Zoldyck",
  nen_type: "Especialização",
  origin: "Montanha Kukuroo",
  first_arc: "Eleição do Presidente Hunter",
  status: "o",
  role: "Irmã de Killua",
  age_group: "Jovem",
  quote: "Nanika pode realizar qualquer desejo.",
  nen_hint: "Poder misterioso ligado a desejos e consequências.",
  silhouetteImage: "/silhouettes/alluka.svg",
},

{
  name: "Kalluto Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Manipulação",
  origin: "Montanha Kukuroo",
  first_arc: "Greed Island",
  status: "Vivo",
  role: "Assassino e membro da Trupe Fantasma",
  age_group: "Jovem",
  quote: "Preciso ficar mais forte.",
  nen_hint: "Usa papéis controlados com Nen.",
  silhouetteImage: "/silhouettes/kalluto.svg",
},

{
  name: "Zigg Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Desconhecido",
  origin: "Montanha Kukuroo",
  first_arc: "Continente Negro",
  status: "Desconhecido",
  role: "Ancestral da família Zoldyck",
  age_group: "Idoso",
  quote: "Poucos sobreviveram ao Continente Negro.",
  nen_hint: "Sobreviveu a expedições extremamente perigosas.",
  silhouetteImage: "/silhouettes/zigg.svg",
},

{
  name: "Gotoh",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Emissão",
  origin: "Montanha Kukuroo",
  first_arc: "Família Zoldyck",
  status: "Morto",
  role: "Mordomo dos Zoldyck",
  age_group: "Adulto",
  quote: "Servir a família é minha missão.",
  nen_hint: "Usa moedas como projéteis extremamente rápidos.",
  silhouetteImage: "/silhouettes/gotoh.svg",
},

{
  name: "Nobunaga Hazama",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Reforço",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Espadachim da Trupe Fantasma",
  age_group: "Adulto",
  quote: "A distância ideal decide uma luta.",
  nen_hint: "Especialista em combate corpo a corpo com espada.",
  silhouetteImage: "/silhouettes/nobunaga.svg",
},
{
  name: "Illumi Zoldyck",
  gender: "Masculino",
  affiliation: "Família Zoldyck",
  nen_type: "Manipulação",
  origin: "Montanha Kukuroo",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Assassino",
  age_group: "Adulto",
  quote: "Matar é só mais uma tarefa.",
  nen_hint: "Controla pessoas usando agulhas especiais.",
  silhouetteImage: "/silhouettes/illumi.svg",
},

{
  name: "Kite",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Especialização",
  origin: "Desconhecida",
  first_arc: "Greed Island",
  status: "Morto",
  role: "Hunter Biológico",
  age_group: "Adulto",
  quote: "Nunca subestime criaturas desconhecidas.",
  nen_hint: "Invoca armas aleatórias através de um palhaço.",
  silhouetteImage: "/silhouettes/kite.svg",
},

{
  name: "Palm Siberia",
  gender: "Feminino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Hunter",
  age_group: "Adulto",
  quote: "O amor pode virar obsessão facilmente.",
  nen_hint: "Usa habilidades ligadas a vigilância e espionagem.",
  silhouetteImage: "/silhouettes/palm.svg",
},

{
  name: "Shalnark",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Manipulação",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Morto",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Informação vale mais do que músculos.",
  nen_hint: "Controla pessoas usando um celular especial.",
  silhouetteImage: "/silhouettes/shalnark.svg",
},

{
  name: "Shoot McMahon",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Hunter",
  age_group: "Adulto",
  quote: "Mesmo assustado, eu continuo lutando.",
  nen_hint: "Manipula mãos flutuantes e prende partes do alvo.",
  silhouetteImage: "/silhouettes/shoot.svg",
},

{
  name: "Wing",
  gender: "Masculino",
  affiliation: "Associação Hunter",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Torre Celestial",
  status: "Vivo",
  role: "Mestre Nen",
  age_group: "Adulto",
  quote: "Nen deve ser aprendido com disciplina.",
  nen_hint: "Especialista em ensinar fundamentos do Nen.",
  silhouetteImage: "/silhouettes/wing.svg",
},

{
  name: "Ponzu",
  gender: "Feminino",
  affiliation: "Associação Hunter",
  nen_type: "Manipulação",
  origin: "Desconhecida",
  first_arc: "Exame Hunter",
  status: "Morto",
  role: "Hunter",
  age_group: "Jovem",
  quote: "Minhas abelhas sempre encontram o alvo.",
  nen_hint: "Controla abelhas usando Nen.",
  silhouetteImage: "/silhouettes/ponzu.svg",
},

{
  name: "Tonpa",
  gender: "Masculino",
  affiliation: "Exame Hunter",
  nen_type: "Desconhecido",
  origin: "Desconhecida",
  first_arc: "Exame Hunter",
  status: "Vivo",
  role: "Sabotador de candidatos",
  age_group: "Adulto",
  quote: "Novatos sempre caem nos mesmos truques.",
  nen_hint: "Especialista em sabotar participantes.",
  silhouetteImage: "/silhouettes/tonpa.svg",
},
{
  name: "Feitan Portor",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Transmutação",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Dor deve ser retribuída com dor.",
  nen_hint: "Transforma dano sofrido em calor destrutivo.",
  silhouetteImage: "/silhouettes/feitan.svg",
},

{
  name: "Machi Komacine",
  gender: "Feminino",
  affiliation: "Trupe Fantasma",
  nen_type: "Transmutação",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulta",
  quote: "Minhas linhas nunca erram o alvo.",
  nen_hint: "Cria fios extremamente resistentes usando Nen.",
  silhouetteImage: "/silhouettes/machi.svg",
},

{
  name: "Phinks Magcub",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Reforço",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Quanto mais giro, mais forte fica.",
  nen_hint: "Aumenta o poder de seus golpes girando o braço.",
  silhouetteImage: "/silhouettes/phinks.svg",
},

{
  name: "Franklin Bordeau",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Emissão",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Violência resolve muita coisa.",
  nen_hint: "Dispara rajadas de aura pelos dedos amputados.",
  silhouetteImage: "/silhouettes/franklin.svg",
},

{
  name: "Shizuku Murasaki",
  gender: "Feminino",
  affiliation: "Trupe Fantasma",
  nen_type: "Conjuração",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulta",
  quote: "Eu esqueço das coisas muito rápido.",
  nen_hint: "Usa um aspirador que absorve quase qualquer coisa.",
  silhouetteImage: "/silhouettes/shizuku.svg",
},

{
  name: "Bonolenov Ndongo",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Conjuração",
  origin: "Meteor City",
  first_arc: "Formigas Quimera",
  status: "Vivo",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "A música do guerreiro ecoa no campo de batalha.",
  nen_hint: "Usa sons e dança para criar ataques poderosos.",
  silhouetteImage: "/silhouettes/bonolenov.svg",
},

{
  name: "Pakunoda",
  gender: "Feminino",
  affiliation: "Trupe Fantasma",
  nen_type: "Especialização",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Morto",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulta",
  quote: "Memórias também podem ser armas.",
  nen_hint: "Lê e compartilha memórias através de balas Nen.",
  silhouetteImage: "/silhouettes/pakunoda.svg",
},

{
  name: "Uvogin",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Reforço",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Morto",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Força absoluta destrói qualquer estratégia.",
  nen_hint: "Poder físico monstruoso e resistência extrema.",
  silhouetteImage: "/silhouettes/uvogin.svg",
},

{
  name: "Kortopi",
  gender: "Masculino",
  affiliation: "Trupe Fantasma",
  nen_type: "Conjuração",
  origin: "Meteor City",
  first_arc: "Yorknew City",
  status: "Morto",
  role: "Membro da Trupe Fantasma",
  age_group: "Adulto",
  quote: "Cópias perfeitas também possuem utilidade.",
  nen_hint: "Cria duplicatas físicas de objetos.",
  silhouetteImage: "/silhouettes/kortopi.svg",
},
];